{% set name = "quantities" %}
{% set version = "0.16.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quantities-{{ version }}.tar.gz
  sha256: 1f7c24f10d9ff57ddf751a358ea2fdfa9914516722f06a788ef4a2924c77d21c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20

test:
  imports:
    - quantities
    - quantities.constants
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://python-quantities.readthedocs.io/
  summary: Support for physical quantities with units, based on numpy
  doc_url: https://pythonhosted.org/quantities/
  license: BSD-Protection
  license_file: license.rst

extra:
  recipe-maintainers:
    - ocefpaf
