{% set version = "0.12.3" %}

package:
  name: quantities
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/quantities/quantities-{{ version }}.tar.gz
  sha256: 582f3c7aeba897846761e966615e01202a5e5d06add304492931b05085d19883

build:
  number: 0
  script: python -m pip install --no-deps .
  noarch: python

requirements:
  build:
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - quantities
    - quantities.constants
    - quantities.units

about:
  home: http://python-quantities.readthedocs.org/en/latest/
  license: BSD 3-Clauses
  summary: 'Physical quantities with units, based upon numpy.'

extra:
  recipe-maintainers:
      - ocefpaf
