{% set name = "quantities" %}
{% set version = "0.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quantities-{{ version }}.tar.gz
  sha256: c9d688e8719720654187a6a83425e7d54f427d7465e03c49f3da53befd20074b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20

test:
  imports:
    - quantities
    - quantities.constants
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://python-quantities.readthedocs.io/
  summary: Support for physical quantities with units, based on numpy
  doc_url: https://pythonhosted.org/quantities/
  license: BSD-Protection
  license_file: license.rst

extra:
  recipe-maintainers:
    - ocefpaf
