{% set version = "0.12.5" %}

package:
  name: quantities
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/quantities/quantities-{{ version }}.tar.gz
  sha256: 67546963cb2a519b1a4aa43d132ef754360268e5d551b43dd1716903d99812f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - quantities
    - quantities.constants
    - quantities.units

about:
  home: http://python-quantities.readthedocs.org/en/latest/
  license: BSD-3-Clauses
  license_file: license.rst
  summary: Physical quantities with units, based upon numpy

extra:
  recipe-maintainers:
    - ocefpaf
