{% set name = "quantities" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quantities-{{ version }}.tar.gz
  sha256: b5cbe363e27dc6d16abeba9fab7a5c98775d81b7d7f16cc691ba00041e02e1d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - quantities
    - quantities.constants
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://python-quantities.readthedocs.io/
  summary: Support for physical quantities with units, based on numpy
  doc_url: https://pythonhosted.org/quantities/
  license: BSD-Protection
  license_file: license.rst

extra:
  recipe-maintainers:
    - ocefpaf
