{% set name = "quantities" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quantities-{{ version }}.tar.gz
  sha256: 9ea31e2a0d7517cf24d546b14146def9292639993a616cca61b875ef796b4b2b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - numpy >=1.20

test:
  imports:
    - quantities
    - quantities.constants
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://python-quantities.readthedocs.io/
  summary: Support for physical quantities with units, based on numpy
  doc_url: https://pythonhosted.org/quantities/
  license: BSD-Protection
  license_file: license.rst

extra:
  recipe-maintainers:
    - ocefpaf
