travis:
  secure:
    BINSTAR_TOKEN: BI48KZDdO3w9r1N3WCMEeOCPKNW7aqexjKcJx7c1S/Bd+Tcj2u34G2qj0iLKBYAbQjRvD8GL9m29ZT1UpHcMdS+h9d7rdleR9OwGjJ5O+/MUSC8hVpIwCkoGqw9t8WaNrbDPLRBVQdyfmx8T7zgyIk4B3boKZA1ZjzlJImJd3sj2A81Mqb7+o0x2h/VrO3Eba7K1qFZvWMGmn2ltQxleWFj04P+pGpDutsB39JBCSqcWfAqj77frLA4S9hOs5NCqRS77/8LLdP19ilnkwg2n761yVMVnALvT/7QWO1JrDwzgDHRzuytvQLfddMyxdT8y6G8l/F1bDqdGDpEPwV6n7twq2UwFYR6PhGm11A47cfCH/j/SHCHbmgHNlcens656deyYOq4zZ8cTrvHY2PAQnC+thFf8T09hppHh7/L9fMvaPU5nzra2w0Z9e7mZv8dtkMAiN1lAGnwEgwrJJVcg0Y2vMG04j4HfJlP7wQrBrf/wUinctdiOWqnbv2G+qM10+AYek0Gs51AzJjXI8OE1gJ9Oisq5ypXWX21eYRAzINPXULTAab2P3AXV1COKqRNMBMwSCHP733uznji/uBscpDi459reznMXMsjkE4UKO7BAK+ls7q3Tpo1EQB14bc2gPF2lZqsSnGKrkFU7nPYkQzi9uZszzafisvL+/3g/Ax0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
